name: "index-digest action - database performance regression testing"
author: "@macbre"
description: "An action to run https://github.com/macbre/index-digest"
# https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#branding
branding:
  icon: "database"
  color: "green"
inputs:
  index-digest-version:
    description: "The version of index-digest to install"
    required: true
    default: "1.4.0"
    
  index-digest-dsn:
    description: "DSN pointing at the database to check"
    require: true

  index-digest-checks:
    description: "Which index-digest checks to perform"
    require: true
    default: "redundant_indices,missing_primary_index,not_used_indices,queries_not_using_index,queries_using_filesort,queries_using_temporary,queries_using_full_table_scan"

  index-digest-report-file:
    description: "Where to save YAML report file"
    required: true
    default: "/tmp/index-digest.yml"

runs:
  using: "composite"
  steps:
    # https://hub.docker.com/r/macbre/index-digest
    - shell: bash 
      run: |
        echo "Using index-version v${{ inputs.index-digest-version }} ..."
        env | sort
        docker pull macbre/index-digest:${{ inputs.index-digest-version }}

    - shell: bash
      run: |
        docker run --network=host -t macbre/index-digest:${{ inputs.index-digest-version }} \
          --checks=${{ inputs.index-digest-checks }} \
          --format=yaml \
          ${{ inputs.index-digest-dsn }} | tee ${{ inputs.index-digest-report-file }}
