name: "index-digest"
author: "@macbre"
description: "An action to run https://github.com/macbre/index-digest"
# https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#branding
branding:
  icon: "database"
  color: "green"
inputs:
  index-digest-version:
    description: "The version of index-digest to install"
    required: true
    default: "1.4.0"
    
  index-digest-dsn:
    description: "DSN pointing at the database to check"
    require: true

  index-digest-sql-log:
    description: "File with SQL queries to check against the database"
    require: false
    default: "/tmp/index_digest_empty_log.sql"

  index-digest-checks:
    description: "Which index-digest checks to perform"
    require: true
    default: "redundant_indices,missing_primary_index,not_used_indices,queries_not_using_index,queries_using_filesort,queries_using_temporary,queries_using_full_table_scan"

  index-digest-report-file:
    description: "Where to save YAML report file"
    required: true
    default: "/tmp/index-digest.yml"

# https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#outputs-for-composite-run-steps-actions
outputs:
  number-of-issues:
    description: 'Number of issues reported'
    value: ${{ steps.process-the-report-file.outputs.number-of-issues }}

runs:
  using: "composite"
  steps:
    # https://hub.docker.com/r/macbre/index-digest
    - shell: bash
      id: pull-and-set-up-index-digest-environment
      run: |
        echo "Using index-version ${{ inputs.index-digest-version }} ..."
        docker pull macbre/index-digest:${{ inputs.index-digest-version }}

        echo "Using SQL log file: ${{ inputs.index-digest-sql-log }} ..."

        # create an empty SQL log file (will be used when "index-digest-sql-log" is not provided)
        touch /tmp/index_digest_empty_log.sql

    - shell: bash
      id: run-index-digest
      run: |
        docker run --network=host --volume="${{ inputs.index-digest-sql-log }}:/tmp/log.sql:ro" \
          -t macbre/index-digest:${{ inputs.index-digest-version }} \
          --checks=${{ inputs.index-digest-checks }} \
          --sql-log=/tmp/log.sql \
          --format=yaml \
          ${{ inputs.index-digest-dsn }} | tee ${{ inputs.index-digest-report-file }}

    # process the report file
    # https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#outputs
    - shell: bash
      id: process-the-report-file
      run: |
        number_of_issues=$(egrep '^\- type:' -c ${{ inputs.index-digest-report-file }})
        echo "Number of reported issues: ${number_of_issues}"

        echo "::set-output name=number-of-issues::${number_of_issues}"
